### PR TITLE
DM-18036: Switch to HTM reference

### PR DESCRIPTION
**Pull request by SimonKrughoff**

### CODE REVIEW

**Comment by timj** [comment]
Can you add a `.gitattributes` file to declare that the FITS files are binaries?

**Comment by SimonKrughoff** [comment]
You mean you want me to put them in `git-lfs`?

**Comment by timj** [comment]
No. I mean to create a `.gitattributes` file.

**Comment by timj** [comment]
See e.g. https://github.com/lsst/daf_butler/blob/master/.gitattributes

**Pull request merged**
