### PR TITLE
DM-10765: Replace existing WCS classes with SkyWcs

### PR DESCRIPTION
**Pull request by r-owen**
Centroids have slightly different positions

### CODE REVIEW

**Comment by RobertLuptonTheGood** [comment]
Can you expand on this comment?  Which centroids shifted, and by how much?

**Comment by r-owen** [comment]
Centroids in the first column shifted by about 1e-5 pixels

**Comment by RobertLuptonTheGood** [comment]
Why did Wcs changes move the centroids?  Or is this a round-trip test?

**Comment by r-owen** [comment]
I don't know in detail. There are probably small numerical differences between wcslib and AST. For WCS that use something other than ICRS then different libraries handle that subtly differently, and SkyWcs also normalizes Dec, RA to RA, Dec (relevant for SDSS) and I don't know the details of how it does that; it creates a new mapping and there may be slight numerical changes caused by that.

**Comment by RobertLuptonTheGood** [comment]
So this is a round-trip test?  I'm a bit confused because you quoted the centroid shift in pixels, which sounds like the image side of the problem.

**Comment by r-owen** [comment]
I was wrong. The numbers differ for measured RA and Dec. I just computed statistics and they are:
```
Angular separation on the sky for the measured positions
mean    0.00022 arcsec
std dev 0.00010 arcsec
min     0.00003 arcsec
max     0.00050 arcsec
```
I do not know where the differences come from. They are small enough I didn't feel it was worth spending a lot of time on.

**Comment by RobertLuptonTheGood** [comment]
Those are small but not negligible (i.e. they are much larger than GAIA errors).  Still, I think it's OK to let this slip for now, especially as some of the problem may be in wcslib.

When we test the astrometry, though, relative astrometry over the LSST or HSC focal plane must not have numerical errors as large as this (this'll be a different test than the one you're carrying out here).

**Pull request merged**
